declare enum marketplaceId {
    default = "EBAY-GB",
    ebayUS = "EBAY-US",
    ebayENCA = "EBAY-ENCA",
    ebayGB = "EBAY-GB",
    ebayAU = "EBAY-AU",
    ebayAT = "EBAY-AT",
    ebayFRBE = "EBAY-FRBE",
    ebayFR = "EBAY-FR",
    ebayDE = "EBAY-DE",
    ebayMotor = "EBAY-MOTOR",
    ebayIT = "EBAY-IT",
    ebayNLBE = "EBAY-NLBE",
    ebayNL = "EBAY-NL",
    ebayES = "EBAY-ES",
    ebayCH = "EBAY-CH",
    ebayHK = "EBAY-HK",
    ebayIN = "EBAY-IN",
    ebayIE = "EBAY-IE",
    ebayMY = "EBAY-MY",
    ebayFRCA = "EBAY-FRCA",
    ebayPH = "EBAY-PH",
    ebayPL = "EBAY-PL",
    ebaySG = "EBAY-SG"
}
export default marketplaceId;
